services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: status-manager-production
    image: status-manager-production
    env_file:
      - .env
    tty: true
    stdin_open: true
    environment:
      RCON_HOST: ${RCON_HOST}
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: ${RCON_PORT}
    volumes:
      - server-gartic:/data:ro
      - /data/logs/latest.log:/logs/latest.log
      - /data/world/stats:/world/stats
    restart: always
    networks:
      - request

volumes:
  server-gartic:
    external: true

networks:
  connection-gartic:
    external: true