services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-prod
    image: discord-bot:prod
    volumes:
      - "D:/Minecraft Servers/Server-Container/Servidor/world/stats:/data/world/stats"
      - "D:/Minecraft Servers/Server-Container/Servidor/logs/latest.log:/data/logs/latest.log"
      # Mudar diretorio para stats do mundo minecraft : /data/world/stats
      # Mudar diretorio para logs do servidor minecraft : /data/logs/latest.log
    env_file:
      - .env
    restart: always
    tty: true
    stdin_open: true