services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-dev
    image: discord-bot:dev
    volumes:
      - "D:/Minecraft Servers/TESTES/Servidor-testes/Servidor/world/stats:/data/world/stats"
      - "D:/Minecraft Servers/TESTES/Servidor-testes/Servidor/logs/latest.log:/data/logs/latest.log"
    env_file:
      - .env.dev  # Arquivo de variáveis de ambiente específicas para desenvolvimento
    tty: true
    stdin_open: true